eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 4444
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /zuul-a/**
      serviceId: service-ribbon
    api-b:
      path: /zuul-b/**
      serviceId: hello-service

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
    health:
      show-details: always #默认是never