server:
  port: 1111
  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不像注册中心注册自己
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #map类型 设置与Eureka Server交互的地址，查询服务和注册服务都要依赖它

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
    health:
      show-details: always #默认是never